MUSIC_TRACKS = [
    {
        "title": "Aq Gulder",
        "artist": "Jangali",
        "duration": 191,
        "plays": 820000,
        "genre": "Pop",
        "language": "Kazakh",
        "cover": "AG",
        "audio_file": "Jangali - Aq Gulder Master 2.wav",
    },
    {
        "title": "Endi Men",
        "artist": "Jangali",
        "duration": 183,
        "plays": 760000,
        "genre": "Pop",
        "language": "Kazakh",
        "cover": "EM",
        "audio_file": "Jangali - endi men.wav",
    },
    {
        "title": "Qara Kozin",
        "artist": "Jangali",
        "duration": 208,
        "plays": 910000,
        "genre": "Pop",
        "language": "Kazakh",
        "cover": "QK",
        "audio_file": "Jangali - Qara kozin 3.wav",
    },
    {
        "title": "Sezimim",
        "artist": "Jangali",
        "duration": 210,
        "plays": 880000,
        "genre": "Pop",
        "language": "Kazakh",
        "cover": "SZ",
        "audio_file": "Jangali - Sezimim 3.wav",
    },
    {
        "title": "Jurek Ani",
        "artist": "Zhan Malikov",
        "duration": 183,
        "plays": 690000,
        "genre": "Kazakh Pop",
        "language": "Kazakh",
        "cover": "JA",
        "audio_file": "Jürek änı .mp3",
    },
    {
        "title": "Light",
        "artist": "SEN",
        "duration": 232,
        "plays": 640000,
        "genre": "Electronic",
        "language": "English",
        "cover": "LT",
        "audio_file": "SEN - LIGHT BND mix 2025 new version.wav",
    },
    {
        "title": "Tym Kesh",
        "artist": "Mr.Kuna feat Zhangali Malikov",
        "duration": 132,
        "plays": 720000,
        "genre": "Hip-Hop KZ",
        "language": "Kazakh",
        "cover": "TK",
        "audio_file": "Tym kesh - Mr.Kuna feat Zhangali Malikov.wav",
    },
    {
        "title": "Zhonushka",
        "artist": "Zhan Malikov",
        "duration": 194,
        "plays": 970000,
        "genre": "Kazakh Pop",
        "language": "Kazakh",
        "cover": "ZH",
        "audio_file": "Zhan Malikov - Zhonushka final mix 2025.mp3",
    },
    {
        "title": "Это ты",
        "artist": "Zhan Malikov",
        "duration": 122,
        "plays": 830000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "ET",
        "audio_file": "Zhan Malikov - ЭТО ТЫ   2026.wav",
    },
    {
        "title": "Mama",
        "artist": "Zhan Malikov",
        "duration": 216,
        "plays": 1100000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "MA",
        "audio_file": "ZHAN MALIKOV MAMA 2025 finish mix с диессером.wav",
    },
    {
        "title": "Oina Oina",
        "artist": "Zhan Malikov",
        "duration": 182,
        "plays": 1040000,
        "genre": "Dance",
        "language": "Kazakh",
        "cover": "OO",
        "audio_file": "Zhan Malikov OINA OINA finish mix 2026 2 varik.wav",
    },
    {
        "title": "Алматының арулары",
        "artist": "Zhan Malikov",
        "duration": 165,
        "plays": 780000,
        "genre": "Kazakh Pop",
        "language": "Kazakh",
        "cover": "AA",
        "audio_file": "Алматының арулары .mp3",
    },
    {
        "title": "Ангел Бес",
        "artist": "Zhan Malikov",
        "duration": 175,
        "plays": 590000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "AB",
        "audio_file": "Ангел_Бес.mp3",
    },
    {
        "title": "100 шагов назад",
        "artist": "Арман",
        "duration": 186,
        "plays": 540000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "100",
        "audio_file": "Арман - 100 шагов назад .mp3",
    },
    {
        "title": "Восточная красавица",
        "artist": "Zhan Malikov",
        "duration": 158,
        "plays": 930000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "VK",
        "audio_file": "Восточная красавица - Zhan Malikov  2023 n.wav",
    },
    {
        "title": "Кандалы",
        "artist": "Zhan Malikov",
        "duration": 179,
        "plays": 570000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "KA",
        "audio_file": "Кандалы.mp3",
    },
    {
        "title": "Корни Чуйской долины",
        "artist": "Zhan Malikov",
        "duration": 166,
        "plays": 520000,
        "genre": "Folk Pop",
        "language": "Russian",
        "cover": "KD",
        "audio_file": "Корни Чуйской долины_.mp3",
    },
    {
        "title": "Любовь ошибка",
        "artist": "Zhan Malikov",
        "duration": 127,
        "plays": 510000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "LO",
        "audio_file": "Любовь ошибка .mp3",
    },
    {
        "title": "Моё время",
        "artist": "Zhan Malikov",
        "duration": 162,
        "plays": 560000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "MV",
        "audio_file": "Моё время .mp3",
    },
    {
        "title": "Моя муза - моя мелодия",
        "artist": "Zhan Malikov",
        "duration": 233,
        "plays": 740000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "MM",
        "audio_file": "Моя муза - моя мелодия .mp3",
    },
    {
        "title": "Не идеальный",
        "artist": "Zhan Malikov",
        "duration": 162,
        "plays": 620000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "NI",
        "audio_file": "Не идеальный  (1).mp3",
    },
    {
        "title": "Не отпускай",
        "artist": "Zhan Malikov",
        "duration": 155,
        "plays": 600000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "NO",
        "audio_file": "Не отпускай .mp3",
    },
    {
        "title": "Обычные люди",
        "artist": "Zhan Malikov",
        "duration": 129,
        "plays": 490000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "OL",
        "audio_file": "Обычные люди .mp3",
    },
    {
        "title": "Отпусти меня",
        "artist": "Zhan Malikov",
        "duration": 270,
        "plays": 690000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "OM",
        "audio_file": "Отпусти меня финал.mp3",
    },
    {
        "title": "Фильтры маски",
        "artist": "Zhan Malikov",
        "duration": 213,
        "plays": 650000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "FM",
        "audio_file": "Фильтры_маски.mp3",
    },
    {
        "title": "Флешбеки",
        "artist": "Zhan Malikov",
        "duration": 199,
        "plays": 670000,
        "genre": "Pop",
        "language": "Russian",
        "cover": "FB",
        "audio_file": "Флешбеки  (1).mp3",
    },
]

ARTIST_DEFAULTS = {
    "Jangali": {
        "bio": "Поп-артист с актуальными казахстанскими релизами.",
        "genre": "Pop",
        "country": "Kazakhstan",
        "city": "Almaty",
        "image": "JG",
        "followers": 940000,
    },
    "Zhan Malikov": {
        "bio": "Автор и исполнитель локальной коллекции MoodStream.",
        "genre": "Pop",
        "country": "Kazakhstan",
        "city": "Almaty",
        "image": "ZM",
        "followers": 1280000,
    },
    "SEN": {
        "bio": "Электронное звучание и свежие студийные миксы.",
        "genre": "Electronic",
        "country": "Kazakhstan",
        "city": "Astana",
        "image": "SN",
        "followers": 430000,
    },
    "Mr.Kuna feat Zhangali Malikov": {
        "bio": "Коллаборация на стыке попа и Hip-Hop KZ.",
        "genre": "Hip-Hop KZ",
        "country": "Kazakhstan",
        "city": "Almaty",
        "image": "MK",
        "followers": 510000,
    },
    "Арман": {
        "bio": "Русскоязычный поп-релиз для каталога MoodStream.",
        "genre": "Pop",
        "country": "Kazakhstan",
        "city": "Almaty",
        "image": "AR",
        "followers": 380000,
    },
}

PLAYLISTS = [
    {
        "name": "Все локальные треки",
        "description": "Полная коллекция аудиофайлов из проекта",
        "cover": "ALL",
        "type": "editorial",
        "creator": "MoodStream",
        "track_indexes": list(range(len(MUSIC_TRACKS))),
    },
    {
        "name": "Zhan Malikov Collection",
        "description": "Треки Zhan Malikov и близкие релизы",
        "cover": "ZM",
        "type": "editorial",
        "creator": "MoodStream",
        "track_indexes": [
            index
            for index, track in enumerate(MUSIC_TRACKS)
            if track["artist"] == "Zhan Malikov"
        ],
    },
    {
        "name": "Jangali Singles",
        "description": "Свежие релизы Jangali",
        "cover": "JG",
        "type": "editorial",
        "creator": "MoodStream",
        "track_indexes": [
            index for index, track in enumerate(MUSIC_TRACKS) if track["artist"] == "Jangali"
        ],
    },
    {
        "name": "Танцевальная волна",
        "description": "Энергичные треки для дороги и вечера",
        "cover": "DN",
        "type": "thematic",
        "creator": "MoodStream",
        "track_indexes": [5, 6, 10, 14, 24, 25],
    },
]

ALBUMS = [
    {
        "title": "MoodStream Local Collection",
        "artist": "Various Artists",
        "cover": "MS",
        "year": 2026,
        "track_indexes": list(range(len(MUSIC_TRACKS))),
    },
    {
        "title": "Jangali Studio Masters",
        "artist": "Jangali",
        "cover": "JS",
        "year": 2026,
        "track_indexes": [0, 1, 2, 3],
    },
    {
        "title": "Zhan Malikov 2025-2026",
        "artist": "Zhan Malikov",
        "cover": "ZM",
        "year": 2026,
        "track_indexes": [
            index
            for index, track in enumerate(MUSIC_TRACKS)
            if track["artist"] == "Zhan Malikov"
        ],
    },
]
