# Generated by Django 5.2.14 on 2026-05-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='track',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='Создано с помощью ИИ'),
        ),
        migrations.AddField(
            model_name='track',
            name='arranger',
            field=models.CharField(blank=True, max_length=500, verbose_name='Аранжировщик'),
        ),
        migrations.AddField(
            model_name='track',
            name='copyright',
            field=models.CharField(blank=True, max_length=500, verbose_name='Авторское право'),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка песни'),
        ),
        migrations.AddField(
            model_name='track',
            name='explicit',
            field=models.BooleanField(default=False, verbose_name='Нецензурные слова'),
        ),
        migrations.AddField(
            model_name='track',
            name='label_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название лейбла'),
        ),
        migrations.AddField(
            model_name='track',
            name='lyrics_author',
            field=models.CharField(blank=True, max_length=500, verbose_name='Автор слов'),
        ),
        migrations.AddField(
            model_name='track',
            name='mixing_engineer',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сведение'),
        ),
        migrations.AddField(
            model_name='track',
            name='music_author',
            field=models.CharField(blank=True, max_length=500, verbose_name='Автор музыки'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Имя артиста'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='app.artist', verbose_name='Артист (из каталога)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код обложки (старое)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Секунды', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(max_length=255, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='track',
            name='language',
            field=models.CharField(choices=[('Kazakh', 'Казахский'), ('Russian', 'Русский'), ('English', 'Английский'), ('Other', 'Другой')], default='Kazakh', max_length=50, verbose_name='Язык сингла'),
        ),
        migrations.AlterField(
            model_name='track',
            name='plays',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Прослушиваний'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название сингла'),
        ),
    ]
