# Generated by Django 5.2.14 on 2026-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_album_tracks_remove_playlist_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='albums', through='app.AlbumTrack', to='app.track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='app.PlaylistTrack', to='app.track'),
        ),
    ]
